defaults:

  skip_first_eval: False
  logdir: null
  demodir: null
  maxnumdemos: 100
  traindir: null
  evaldir: null
  offline_traindir: ''
  offline_evaldir: ''
  seed: 0
  deterministic_run: False
  steps: 2e6
  parallel: False
  eval_every: 1e4
  eval_episode_num: 10
  log_every: 1e4
  reset_every: 0
  device: 'cuda:0'
  compile: True
  precision: 16
  debug: False
  video_pred_log: True

  # Environment
  task: 'dmc_walker_walk'
  size: [64, 64]
  envs: 1
  action_repeat: 2
  time_limit: 1000
  grayscale: False
  prefill: 2500
  reward_EMA: True
  force_sparse: False

  # Model
  dyn_hidden: 512
  dyn_deter: 512
  dyn_gru_blocks: 8
  dyn_stoch: 32
  dyn_discrete: 32
  dyn_rec_depth: 1
  dyn_mean_act: 'none'
  dyn_std_act: 'sigmoid2'
  dyn_min_std: 0.1
  grad_heads: ['decoder', 'reward', 'cont']
  units: 512
  act: 'SiLU'
  norm: True
  encoder:
    {mlp_keys: '$^', cnn_keys: 'image', act: 'SiLU', norm: True, cnn_depth: 32, kernel_size: 4, minres: 4, mlp_layers: 5, mlp_units: 1024, symlog_inputs: True}
  decoder:
    {mlp_keys: '$^', cnn_keys: 'image', act: 'SiLU', norm: True, cnn_depth: 32, kernel_size: 4, minres: 4, mlp_layers: 5, mlp_units: 1024, cnn_sigmoid: False, image_dist: mse, vector_dist: symlog_mse, outscale: 1.0}
  critic:
    {layers: 2, dist: 'symlog_disc', slow_target: True, slow_target_update: 1, slow_target_fraction: 0.02, lr: 3e-5, eps: 1e-5, grad_clip: 100.0, outscale: 0.0}
  reward_head:
    {layers: 2, dist: 'symlog_disc', loss_scale: 1.0, outscale: 0.0}
  cont_head:
    {layers: 2, loss_scale: 1.0, outscale: 1.0}
  dyn_scale: 0.5
  rep_scale: 0.1
  kl_free: 1.0
  weight_decay: 0.0
  unimix_ratio: 0.01
  initial: 'learned'

  # Training
  batch_size: 16
  batch_length: 64
  train_ratio: 512
  pretrain: 100
  reduce_lr_after_pretraining: True
  model_lr: 1e-4
  opt_eps: 1e-8
  grad_clip: 1000
  dataset_size: 1000000
  opt: 'adam'

  # Behavior.
  discount: 0.997
  discount_lambda: 0.95
  imag_horizon: 15
  imag_gradient: 'dynamics'
  imag_gradient_mix: 0.0
  eval_state_mean: False

  # Exploration
  expl_behavior: 'greedy'
  expl_until: 0
  expl_extr_scale: 0.0
  expl_intr_scale: 1.0
  disag_target: 'stoch'
  disag_log: True
  disag_models: 10
  disag_offset: 1
  disag_layers: 4
  disag_units: 400
  disag_action_cond: False
  action_unimix_ratio: 0.01


  # Director
  skill_shape: [4,4]
  goal_ae_layers: 4
  goal_ae_units: 512
  goal_ae_grad_clip: 100.0
  goal_ae_opt_eps: 1e-6
  goal_ae_lr: 1e-4 # 1e-5 
  goal_ae_wd: 0 # 1e-2 # NOTE: DH applies weight_decay * lr to kernel layers of his MLPs, It looks like there are fewer kernel layers than layers, but in theory every dense layer of weights is a "kernel" layer. The point is that
  # goal_ae_wd_pattern: 'kernel'
  goal_vae_kl: True
  goal_vae_kl_autoadapt: True
  goal_vae_kl_beta: 1.0 # Used when we're not autoadapting
# goal_encoder: {layers: 4, units: 512, act: elu, norm: layer, dist: onehot, outscale: 0.1, unimix: 0.0, inputs: [goal]}
# goal_decoder: {layers: 4, units: 512, act: elu, norm: layer, dist: mse, outscale: 0.1, inputs: [skill]}
  goal_encoder: 
    {layers: 4, units: 512, act: "ELU", norm: "LayerNorm", dist: "onehot", outscale: 0.1} # unimix_ratio: 0.0,
  goal_decoder: 
    {layers: 4, units: 512, act: "ELU", norm: "LayerNorm", dist: "mse", outscale: 0.1} # dist: mse in original
  train_skill_duration: 8
  human_skill_duration: 16
  kl_autoadapt: 
    {impl: mult, scale: 0.0, target: 10.0, min: 1e-5, max: 1.0}
  manager_lr: 3e-5 # 1e-4 # 
  worker_lr: 3e-5 # 1e-4 # 
  manager_grad_clip: 100
  manager_opt_eps: 1e-6
  manager_grad: reinforce
  manager_actent: 0.5
  manager_actor: {act: "SiLU", norm: "LayerNorm", dist: "onehot", outscale: 1.0}
  expl_reward_weight: 0.1
  extr_reward_weight: 1.0                                                                                                                                      
  worker_actor: {act: "SiLU", norm: "LayerNorm", dist: "onehot", outscale: 1.0}
  reward_layers: 2
  cont_layers: 2
  value_layers: 2
  actor_layers: 2
  actent_perdim: True
  actor_init_std: 1.0
  actor_min_std: 0.1
  actor_max_std: 1.0
  actor_temp: 0.1
  expl_amount: 0.0
  collect_dyn_sample: True
  behavior_stop_grad: True
  value_decay: 0.0
  future_entropy: False
  slow_value_target: True
  slow_target_update: 1
  slow_target_fraction: 0.02
  value_lr: 3e-5
  actor_lr: 3e-5 # 3e-5
  human: False

dmc_proprio:
  steps: 5e5
  action_repeat: 2
  envs: 4
  train_ratio: 512
  video_pred_log: false
  encoder: {mlp_keys: '.*', cnn_keys: '$^'}
  decoder: {mlp_keys: '.*', cnn_keys: '$^'}

dmc_vision:
  steps: 1e6
  action_repeat: 2
  envs: 4
  train_ratio: 512
  video_pred_log: true
  encoder: {mlp_keys: '$^', cnn_keys: 'image'}
  decoder: {mlp_keys: '$^', cnn_keys: 'image'}

crafter:
  task: crafter_reward
  step: 1e6
  action_repeat: 1
  envs: 1
  train_ratio: 512
  video_pred_log: true
  dyn_hidden: 1024
  dyn_deter: 4096
  units: 1024
  encoder: {mlp_keys: '$^', cnn_keys: 'image', cnn_depth: 96, mlp_layers: 5, mlp_units: 1024}
  decoder: {mlp_keys: '$^', cnn_keys: 'image', cnn_depth: 96, mlp_layers: 5, mlp_units: 1024}
  reward_head: {layers: 5}
  cont_head: {layers: 5}
  imag_gradient: 'reinforce'

atari100k:
  steps: 4e5
  envs: 1
  action_repeat: 4
  train_ratio: 1024
  video_pred_log: true
  eval_episode_num: 100
  stickey: False
  lives: unused
  noops: 30
  resize: opencv
  actions: needed
  time_limit: 108000

minecraft:
  task: minecraft_diamond
  step: 1e8
  parallel: True
  envs: 16
  # no eval
  eval_episode_num: 0
  eval_every: 1e4
  action_repeat: 1
  train_ratio: 16
  video_pred_log: true
  dyn_hidden: 1024
  dyn_deter: 4096
  units: 1024
  encoder: {mlp_keys: 'inventory|inventory_max|equipped|health|hunger|breath|obs_reward', cnn_keys: 'image', cnn_depth: 96, mlp_layers: 5, mlp_units: 1024}
  decoder: {mlp_keys: 'inventory|inventory_max|equipped|health|hunger|breath', cnn_keys: 'image', cnn_depth: 96, mlp_layers: 5, mlp_units: 1024}
  reward_head: {layers: 5}
  cont_head: {layers: 5}
  imag_gradient: 'reinforce'
  break_speed: 100.0
  time_limit: 36000

memorymaze:
  steps: 1e8
  action_repeat: 2
  task: 'memorymaze_9x9'

  units: 512
  encoder: {cnn_depth: 32, mlp_layers: 3}
  decoder: {cnn_depth: 32, mlp_layers: 3}
  dyn_hidden: 512
  dyn_deter: 4096
  dyn_stoch: 32
  dyn_discrete: 32
  critic: {layers: 3} 
  reward_head: {layers: 1}
  cont_head: {layers: 1}

pinpad_four:
  size: [64, 64]
  task: 'pinpad_four'
  steps: 4e4
  log_every: 1e3
  envs: 8
  train_ratio: 256
  video_pred_log: true
  eval_episode_num: 20
  action_repeat: 1
  time_limit: 150
  encoder: {cnn_depth: 16, mlp_layers: 2}
  decoder: {cnn_depth: 16, mlp_layers: 2}
pusht:
  train_ratio: 256 # 1024 is every step for 16 batch_length and 64 batch_size
  size: [64, 64]
  task: pusht_PushT-v0
  step: 1e5
  time_limit: 300

debug:
  debug: True
  pretrain: 1
  prefill: 1
  batch_size: 10
  batch_length: 20
